name: Continuous Dependency Update

on:
  push:
    branches: [ main ] # or replace 'main' with your branch name
    paths:
      - '.github/workflows/**'
      - 'renovate.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-dependencies

    - name: Install Dependencies
      run: npm install

    - name: Run tests
    uses: actions/test-runner@v1
    with:
      testRunner: jest
